Add cls embeddings
szczurek-lab/jointformer pull request #35
Opened 2024-08-06 08:49 UTC by AdamIzdebski

2024-08-06 15:17 UTC, AdamIzdebski commented
@jano1906 note that cls_embeddings and lm_embeddings have a non-empty intersection in this version of Jointformer

2024-08-08 15:09 UTC, jano1906 commented on jointformer/models/utils.py
> +            return self['cls_embeddings'].mean(dim=-1)
Why _is_cls_token_embedding requires len(cls_ebedding) == 2? Seems odd. Also note that len(tensor) returns tensor.shape[0] so it's the batch size. I don't know what's happening here.

if we don't have cls_embeddings we want to aggregate the lm_embeddings with respect to attention mask, don't change the meaning of cls_embedding based on the count of their dimension. The entity constructing ModelOutput should decide which embeddings are cls and which are lm and if it does not produce cls_embeddings, then ModelOutput should automatically aggregate lm_embeddings based on attention mask.

2024-08-08 15:19 UTC, jano1906 requested changes
https://github.com/szczurek-lab/jointformer/pull/35/files#r1709721948

2024-08-12 15:28 UTC, AdamIzdebski commented on jointformer/models/utils.py
> +            return self['cls_embeddings'].mean(dim=-1)
changed

2024-08-12 15:30 UTC, AdamIzdebski commented on jointformer/models/utils.py
> +            return self['cls_embeddings'].mean(dim=-1)
@jano1906 do you want to change to dataclasses in this or in a new pr?

2024-08-13 17:58 UTC, jano1906 approved these changes

2024-08-13 18:00 UTC, merged