Add regression transformer
szczurek-lab/jointformer pull request #37
Opened 2024-08-14 16:01 UTC by Pankhil07

2024-08-15 11:09 UTC, AdamIzdebski requested changes

2024-08-26 09:05 UTC, AdamIzdebski commented on configs/models/regression_transformer/config.json
> +
done

2024-08-26 09:05 UTC, AdamIzdebski commented on jointformer/models/auto.py
> +                "Moler").from_config(config)
done

2024-08-26 09:05 UTC, AdamIzdebski commented on jointformer/models/regression_transformer.py
> +    def to_guacamole_generator(self, temperature, fraction_to_mask, device, target, *args, **kwargs) -> DistributionMatchingGenerator:
done

2024-08-26 09:05 UTC, AdamIzdebski commented on jointformer/models/regression_transformer.py
> +        self._dataset = self._load_regression_transformer_dataset(filename)
done

2024-08-26 09:07 UTC, AdamIzdebski commented on jointformer/configs/model.py
> +        fraction_to_mask:Optional[float] = None,
to delete

2024-08-26 09:07 UTC, AdamIzdebski commented on jointformer/configs/model.py
> +        self.fraction_to_mask = fraction_to_mask
to delete

2024-09-03 15:29 UTC, AdamIzdebski approved these changes

2024-09-05 15:46 UTC, jano1906 approved these changes

2024-09-05 15:46 UTC, merged